/**
 * Compile-time table inventory shared across all dialects.
 *
 * - BACKUP_TABLES: ordered list for backup/restore (parents before children).
 * - TABLE_COLUMNS: canonical column names per table (final post-migration shape).
 *   Replaces runtime PRAGMA table_info() so cloud dialects (PG/MySQL) can
 *   validate imported backup rows without a dialect-specific introspection.
 *
 * Both are derived from the authoritative SQLite DDL in createTables() and MUST
 * be kept in sync when columns are added. Table names are never user-supplied.
 */

export const BACKUP_TABLES = [
  "providers",
  "users",
  "web_users",
  "api_keys",
  "usage",
  "settings",
  "model_prices",
  "coding_configs",
  "model_restrictions",
  "user_groups",
  "model_mappings",
] as const;

export const TABLE_COLUMNS: Record<string, readonly string[]> = {
  providers: [
    "id",
    "name",
    "api_type",
    "base_url",
    "api_key",
    "user_agent",
    "models",
    "enabled",
    "input_price",
    "output_price",
    "created_at",
    "updated_at",
    "key_strategy",
  ],
  users: [
    "id",
    "tg_user_id",
    "username",
    "is_active",
    "created_at",
    "group_id",
    "expires_at",
    "rpm_override",
    "tpm_override",
    "concurrency_override",
    "daily_token_override",
    "monthly_token_override",
    "daily_cost_override",
    "monthly_cost_override",
  ],
  web_users: [
    "id",
    "username",
    "password_hash",
    "is_admin",
    "is_active",
    "created_at",
  ],
  api_keys: [
    "id",
    "user_id",
    "key",
    "is_active",
    "created_at",
    "expires_at",
    "rpm_override",
    "tpm_override",
    "concurrency_override",
    "daily_token_override",
    "monthly_token_override",
    "daily_cost_override",
    "monthly_cost_override",
  ],
  usage: [
    "id",
    "api_key_id",
    "provider_id",
    "input_tokens",
    "output_tokens",
    "input_cost",
    "output_cost",
    "model",
    "created_at",
  ],
  settings: ["key", "value"],
  model_prices: [
    "id",
    "provider_id",
    "model",
    "input_price",
    "output_price",
    "created_at",
    "updated_at",
  ],
  coding_configs: [
    "id",
    "user_id",
    "is_active",
    "fallback_models",
    "max_retries",
    "session_input_tokens",
    "session_output_tokens",
    "session_input_cost",
    "session_output_cost",
    "session_requests",
    "session_model_counts",
    "created_at",
    "updated_at",
  ],
  model_restrictions: [
    "id",
    "user_id",
    "api_key_id",
    "mode",
    "models",
    "created_at",
    "updated_at",
  ],
  user_groups: [
    "id",
    "name",
    "display_name",
    "rpm_limit",
    "tpm_limit",
    "concurrency_limit",
    "daily_token_limit",
    "monthly_token_limit",
    "daily_cost_limit",
    "monthly_cost_limit",
    "is_default",
    "created_at",
    "updated_at",
    "allowed_models",
  ],
  model_mappings: ["id", "provider_id", "original_model", "display_name"],
};
